# site settings

title: Carlos Espin
description: My Universal Codec and More
taglong: My Universal Codec and More
tagshort: Universal Codec
url: https://www.espin.xyz
baseurl: ""
permalink: pretty
repo: https://github.com/cespin/espin.xyz

# author settings

author:
  name: Carlos Espin
  email: cespin@live.ca
photo: /assets/webp/yo.webp

# social media links

social:
  facebook: carlos.espin
  github: cespin
  instagram: charly8182
  linkedin: espin
  stackoverflow: 16654793/carlos-espin
  twitter: cespinf

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
